FROM tensorflow/tensorflow:2.2.0 as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_api_tf2.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    pip install  --no-cache-dir -r requirements_api_tf2.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./src/app/ml/resnet50_tfs/run_extract_resnet50_tfs.sh /${PROJECT_DIR}/run_extract_resnet50_tfs.sh

RUN chmod +x run_extract_resnet50_tfs.sh && \
    ./run_extract_resnet50_tfs.sh


FROM tensorflow/serving:2.2.0

ENV PROJECT_DIR serving_patterns
ENV MODEL_BASE_PATH=/${PROJECT_DIR}/src/app/ml/resnet50_tfs/model/savedmodel/resnet_v2_50
ENV MODEL_NAME=resnet_v2_50

COPY --from=builder /${PROJECT_DIR}/src/app/ml/resnet50_tfs/model/savedmodel/resnet_v2_50 ${MODEL_BASE_PATH}
EXPOSE 8500
EXPOSE 8501

COPY ./scripts/tf_serving_entrypoint.sh /usr/bin/tf_serving_entrypoint.sh
RUN chmod +x /usr/bin/tf_serving_entrypoint.sh
ENTRYPOINT ["/usr/bin/tf_serving_entrypoint.sh"]