FROM python:3.8.5-slim

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_proxy.txt /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    pip install --no-cache-dir -r requirements_proxy.txt

COPY ./src/api_composition_proxy/ /${PROJECT_DIR}/src/api_composition_proxy/
COPY ./src/jobs/ /${PROJECT_DIR}/src/jobs/
COPY ./src/middleware/ /${PROJECT_DIR}/src/middleware/
COPY ./src/*.py /${PROJECT_DIR}/src/
COPY ./logging/ /${PROJECT_DIR}/logging/

COPY ./src/api_composition_proxy/run_proxy.sh /${PROJECT_DIR}/run_proxy.sh
RUN chmod +x run_proxy.sh

CMD ./run_proxy.sh

