FROM golang:1.15.5-buster

WORKDIR /opt/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    apt-get clean && \
    go get -u github.com/tsenart/vegeta

COPY ./models/data.json /opt/data.json