FROM continuumio/miniconda:latest as builder

ENV PROJECT_DIR serving_patterns
WORKDIR /${PROJECT_DIR}
ADD requirements/requirements_pytorch.txt /${PROJECT_DIR}/
ADD requirements/conda_pytorch.yaml /${PROJECT_DIR}/
RUN apt-get -y update && \
    apt-get -y install apt-utils gcc curl && \
    conda update -n base -c defaults conda && \
    conda env update -f conda_pytorch.yaml && \
    conda install pytorch torchvision cpuonly -c pytorch && \
    conda clean -y --all && \
    pip install  --no-cache-dir -r requirements_pytorch.txt

COPY ./src/ /${PROJECT_DIR}/src/
COPY ./src/app/ml/resnet50_onnx_server/run_extract_resnet50_onnx_server.sh /${PROJECT_DIR}/run_extract_resnet50_onnx_server.sh

RUN chmod +x run_extract_resnet50_onnx_server.sh && \
    ./run_extract_resnet50_onnx_server.sh


FROM  mcr.microsoft.com/onnxruntime/server:latest

ENV PROJECT_DIR serving_patterns
ENV MODEL_BASE_PATH=/${PROJECT_DIR}/src/app/ml/resnet50_onnx_server/model
WORKDIR /${PROJECT_DIR}

COPY --from=builder /${PROJECT_DIR}/src/app/ml/resnet50_onnx_server/model/resnet50v2.onnx ${MODEL_BASE_PATH}/resnet50v2.onnx

WORKDIR /onnxruntime/server/
COPY ./scripts/onnx_runtime_server_entrypoint.sh ./onnx_runtime_server_entrypoint.sh
RUN chmod +x onnx_runtime_server_entrypoint.sh
ENTRYPOINT ["./onnx_runtime_server_entrypoint.sh"]
